### ISSUE TITLE
Possible to use with institutional log-ins?

### ISSUE THREAD

**Issue by mdelhey** [Addono/HathiTrust-downloader#1]
This looks like a great tool. Is there any way to make it work for books which require institutional log-ins?

**Comment by Addono** [comment]
Hmm 🤔 , probably it requires some changes to the code. 

I don't have an institutional account which integrates with HathiTrust, so I'm not completely sure what it would take to get that to work. 

My guess is that they use cookies, so then it could probably be done by:
1. Using a browser to login as usual
2. Copy the cookie from the developers tools
3. Add an additional flag to this command line tool where you can paste the content of this cookie

It won't be the most user-friendly approach (opening a browsers dev-tools can sound daunting), but it will probably be the simplest way to implement it.

Shouldn't be too hard to implement, but I don't have a need for it nor an account to give it a shot, so sadly won't be able to spend time on it.

Feel free to give it a shot though. The entire code-base of this project is literally only 40 lines, where https://github.com/Addono/HathiTrust-downloader/blob/09e140e8bd61459604fcf1d9615e95f34eea10de/hathitrustdownloader/cli.py#L25 is the crucial part where you would need to add a parameter `cookies=` with the value of the cookie(s) needed for authorization. Finding out which cookie/cookies are used by HathiTrust to handle auth would need some investigating.

**Comment by mdelhey** [comment]
Thanks for taking the time to respond! I'll take a look at this when I get the chance.

**Comment by Addono** [comment]
Sure. Feel free to send a PR if you get it to work, or ask something if you're stuck. 

No need to feel pressured to give it a shot though 😄

**Comment by mendelkranz** [comment]
Any chance anyone has gotten this to work?

**Comment by mdelhey** [comment]
I have not. Here's the [process I'm currently using.](http://matthewdelhey.com/inc/hathi.html) I'm not likely to spend the time to figure out how to automate it.

**Comment by mendelkranz** [comment]
Wow thank you. Been looking for something like this for a while now.
