### ISSUE TITLE
Does it only download in PDF?

### ISSUE THREAD

**Issue by Oudwins** [Addono/HathiTrust-downloader#2]
Would it be possible to add an option to download in .txt format? I can try implementing it if not, never coded in python but it should be a simple change.

edit: looks great btw, thanks for sharing!

**Comment by Addono** [comment]
For now, it only downloads individual pages. If they also have them in `txt`, then that should probably be an easy change.

The whole program is only 40 lines, so even without much proficiency in Python you should probably still be able to get the hang.

I suspect that if they have everything in txt as well, then the only thing which needs to be changed is the download url and filename of the outputted document.

https://github.com/Addono/HathiTrust-downloader/blob/6dcdbf989fde2962a92b703f2b1565a15e32a7f1/hathitrustdownloader/cli.py#L18-L21

**Comment by Oudwins** [comment]
Thanks! Yea it looks simple. Ill get around to it maybe next week.
