### ISSUE TITLE
Does it only work with mdp. ids?

### ISSUE THREAD

**Issue by Brae10** [Addono/HathiTrust-downloader#4]
I tried downloading this book, (https://babel.hathitrust.org/cgi/pt?id=hvd.hn2s91&view=1up&seq=9) which has a hvd id and it stays stuck on zero. I've downloaded a few others but they were all mdps. Just wanted to know if mdp was the only supported id.

**Comment by Addono** [comment]
No problems here, at least the first few pages are downloaded when running `hathitrust-downloader hvd.hn2s91 1 5`
