### ISSUE TITLE
Add asynchronous downloading and proxy support

### ISSUE THREAD

**Issue by telugu-boy** [Addono/HathiTrust-downloader#7]
WOndering if you would accept a PR with these added features.

**Comment by telugu-boy** [comment]
As well as PDF merging

**Comment by Addono** [comment]
By all means, go ahead 😄 . 

Although the goal of this downloader will remain to be simple, both to the end-user (such that it's easy to get started) and the 'business logic' of the code (such that it stays relatively straight forward to reason about what the code does, the code).

So, I would strongly prefer code-changes could which are clearly separated from the current control flow, and new features ideally completely skipped over when not enabled. For example, an overly simplistic illustration of the code-layout I would try to get to work for the proxy would be something along the lines of:

```python
def get_request(url):
  proxy = None
  if proxy_feature_enabled: # Whatever logic for picking up on the proxy flag argument in the CLI
    proxy = Proxy()

  return request.get(url, proxy, stream=True)  

# ...
# Then, in the existing main control flow it should be sufficient to only tell the HTTP library 
# to use our wrapped request library without affecting the control flow there more.
  get_request(url)
```

I'm assuming that with async you mean parallel/concurrent downloads? If so, it only makes sense if there's also support to have a list of proxies to switch between. Without it, you already run into IP-based rate-limits in no-time with the current synchronous implementation.

**Comment by Addono** [comment]
I'll close this for inactivity, LMK if you manage to make any progress on the PR :)
